---
- name: Generate response Netca
  template: src=netca12102.rsp.j2 dest=/tmp/netca12102.rsp.j2

- name: Ensure parameters in response file - dbca response file
  lineinfile:
    path: /tmp/netca12102.rsp.j2
    regexp: ^({{ item.name }})=
    line: '{{ item.name }}={{ item.value }}'
    backrefs: true
    state: present
  with_items:
  - name: LOG_FILE
    value: '{{ log_file }}'
  - name: INSTALL_TYPE
    value: '{{ install_type }}'
  - name: LISTENER_NUMBER
    value: '{{ listener_number }}'
  - name: LISTENER_NAMES
    value: '{{ listener_names }}'
  - name: LISTENER_PROTOCOLS
    value: '{{ listener_protocols }}'
  - name: LISTENER_START
    value: '{{ listener_start }}'
  - name: NAMING_METHODS
    value: '{{ naming_methods }}' 
