--- # response file check and generate the response file in target /tmp location
- name: Generate the response file for software only installation
  template: src={{ groupname }}_{{ version }}.rsp.j2  dest=/tmp/{{ groupname }}_{{ version }}.rsp

- name: Ensure parameters in response file - software installation response file
  lineinfile:
    path: /tmp/{{ groupname }}_{{ version }}.rsp
    regexp: ^({{ item.name }})=
    line: '{{ item.name }}={{ item.value }}'
    backrefs: true
    state: present
  with_items:
  - name: UNIX_USER
    value: '{{ user_name }}'
  - name: UNIX_GROUP_NAME
    value: '{{ user_group_name }}'
  - name: ORACLE_HOSTNAME
    value: '{{ oracle_hostname }}'
  - name: INVENTORY_LOCATION
    value: '{{ inventory_location }}'
  - name: ORACLE_HOME
    value: '{{ oracle_home }}'
  - name: ORACLE_BASE
    value: '{{ oracle_base }}'

